### PR TITLE
Add filter plugin

### PR DESCRIPTION
**Pull request by cosmo0920**
I try to implement filter version of rewrite plugin.

But, unfortunately, filter plugin does not have rewriting tag functionality.
This output version of rewrite plugin's modifying tag functionality seems to be important.

Could you review and advice to improve more better filter version of rewrite plugin implementation?
Will filter version of rewrite plugin become useful plugin?
I want to hear your opinion.

Thanks.

### CODE REVIEW

**Comment by kentaro** [comment]
To avoid redundant implementation, consult this PR https://github.com/kentaro/fluent-plugin-extract_query_params/pull/15

**Comment by cosmo0920** [comment]
OK, thanks!
I'll try to extract common code and use it in output/filter plugins.

**Comment by cosmo0920** [comment]
I tried to extract common code as `RewriteRule` class.
How about this class' name and extracting strategy?

**Comment by kentaro** [comment]
Looks fine, and needs a bit more tweaks:

* Ensure whether this code works fine with both fluentd 0.10.x and  0.12.x using Appraisal.
* Don't make the test code redundant.

See https://github.com/kentaro/fluent-plugin-extract_query_params/commit/53a4bad4cabe073706bcc6d35d5778d125d6bb2b for details.

**Comment by cosmo0920** [comment]
> Ensure whether this code works fine with both fluentd 0.10.x and 0.12.x using Appraisal.

Hmm, this repository does not put Travis CI related settings.
Should I send another PR to add Travis CI settings, before adding Appraisal CI settings?

> Don't make the test code redundant.

What does you mean this sentence?
I don't feel current test code contains redundant code.

If output/filter version contains test code which aims to test multiple rewrite patterns, they have different testing target.
Ah..., perhaps, you mean rewrite related tests are redundant? https://github.com/kentaro/fluent-plugin-rewrite/pull/8/files#diff-306bc1565e62f17d48260e0fd5ba06c9R30

**Comment by kentaro** [comment]
> Hmm, this repository does not put Travis CI related settings

I'll add it after merging this PR :bow: 

> Ah..., perhaps, you mean rewrite related tests are redundant?

Yes. If not so, go ahead.

**Comment by cosmo0920** [comment]
> See kentaro/fluent-plugin-extract_query_params@53a4bad for details.

BTW, this commit contains appraisals example generated code.
Is this intended?

**Comment by cosmo0920** [comment]
>> Hmm, this repository does not put Travis CI related settings

> I'll add it after merging this PR :bow:

I've registered another PR to add .travis.yml with Appraisals gem.
Please review and merge it? :wink: 

After #9 is merged, I'll rebase this PR.

**Comment by cosmo0920** [comment]
>> Ah..., perhaps, you mean rewrite related tests are redundant?

> Yes. If not so, go ahead.

I think that rewrite related tests is not redundant.
Because output version of rewrite tests modify tag and records, but filter version of rewrite tests do not modify tag, just modify records. They are different test cases, don't you?

**Comment by kentaro** [comment]
Got it!

**Comment by cosmo0920** [comment]
Do you have any concerns?

**Comment by kayrus** [comment]
I'm also interested in this pull request to resolve the #12

**Comment by kentaro** [comment]
Merged it tentatively to proceed it.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
