### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, @kentaro !

I've migrated this plugin to use v0.14 API.
**Notice:** This PR contains BRAKING CHANGES.

Even if this PR is acceptable, please don't merge immediately.

First, we should release dependency Fluentd version locked version to ensure lock dependency for Fluentd v0.12.
And then, please merge this PR.
Finally, we should bump up dependent Fluentd version to 0.14.4 or later, bump up major version, and publish to ruby gems.

In more detail, about releasing process for v0.14 plugin and non-buffered output v0.14 plugin, please refer to these documents:
- http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12
- http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12#non-buffered-output-plugins

### CODE REVIEW

**Comment by cosmo0920** [comment]
BTW: Fluentd v0.14 does not support tag manipulation in its plugin helpers.

I think that it is better to migrate into filter like as #8.

Because Fluentd developer says that "don't manipulation tag in output plugin, use labels. If a plugin can implement same feature in output and filter plugin, we recommend to use filter and abandon output plugin." See (twitter): [Twitter | status/773068341804011520](https://twitter.com/tagomoris/status/773068341804011520)

**Comment by kentaro** [comment]
Got it. Please tell me when things get done.

**Comment by kentaro** [comment]
Got conflicted...

**Comment by cosmo0920** [comment]
I'll resolve this conflicts in next week.

**Comment by kentaro** [comment]
🙏

**Comment by cosmo0920** [comment]
I've rebased this PR -- but I also noticed that filter version of this plugin should migrate to v0.14 API.
Please leave it as-is for now. :bow:

**Comment by cosmo0920** [comment]
And I feel that output version of plugin should migrate to v0.14 API and provide until Fluentd v2 (the one after the next version of v0.14).

**Comment by cosmo0920** [comment]
I've also migrated filter version of this plugin to use v0.14 API.
Could you take a look again this PR?

**Comment by kentaro** [comment]
Released as v0.1.0! Thank you!

**Comment by cosmo0920** [comment]
Wow, thanks for releasing new version!! :yum:

**Pull request merged**
